basePath: /api
definitions:
  controllers.OutfitResponse:
    properties:
      asset_path:
        type: string
      id:
        type: integer
      name:
        type: string
      series_id:
        type: integer
      type:
        type: string
    type: object
  controllers.UserLoginRequest:
    properties:
      id:
        type: integer
      password:
        type: string
    required:
    - id
    - password
    type: object
  controllers.UserLoginResponse:
    properties:
      token:
        type: string
    type: object
  controllers.UserRegisterRequest:
    properties:
      name:
        maxLength: 20
        minLength: 4
        type: string
    required:
    - name
    type: object
  controllers.UserRegisterResponse:
    properties:
      id:
        type: integer
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: CAT Backend
  version: "1.0"
paths:
  /api/outfits:
    get:
      description: 全ての衣装情報を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.OutfitResponse'
            type: array
      security:
      - BearerAuth: []
      summary: 全衣装取得
      tags:
      - outfits
  /users/login:
    post:
      consumes:
      - application/json
      description: 'IDとパスワードで認証し、JWTトークンを返す。このJWTトークンは Authorization: Bearer <token>
        としてヘッダーに付加してください。'
      parameters:
      - description: ユーザーログインリクエスト
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserLoginResponse'
      summary: ユーザーログイン
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: 新規ユーザーを登録し、IDとパスワードを返す
      parameters:
      - description: ユーザー登録リクエスト
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserRegisterResponse'
      summary: ユーザー登録
      tags:
      - users
securityDefinitions:
  JTW:
    description: 'Bearer: に続いてトークンを入力してください'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
